FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build
WORKDIR /app
COPY *.sln .
COPY WebApplication1/*.csproj ./WebApp/
COPY WebApplication1/*.config ./WebApp/

WORKDIR /app/WebApp

RUN nuget restore -PackagesDirectory ../packages

COPY WebApplication1/. ./
WORKDIR /app/WebApp

RUN msbuild /p:Configuration=Release -r:False

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019 as runtime
WORKDIR /inetpub/wwwroot
COPY --from=build /app/WebApp/. ./